import lodash from 'lodash';

export const questions = [
  'Jaki jest twój ulubiony zapach?',
  'Najważniejszą rzeczą w potencjalnym partnerze jest?',
  'Twoja ulubiona postać z bajki?',
  'Musisz zaśpiewać karaoke, jaką piosenkę wybierasz?',
  'Jeśli miałbyś stać się sławny, to za co?',
  'Możesz jeść tylko jedno danie do końca życia, jakie?',
  'Jaki byłby tytuł twojej autobiografii?',
  'Jaki jest twój największy lęk?',
  'Chcesz upiec najgorsze ciastka pod słońcem, jaki wybierasz smak?',
  'Jakiego emoji używasz najczęściej?',
  'Dokończ zdanie: Chciałabym, żeby każdy mógł...',
  'Oprócz owadów i pająków, jakie zwierzęta najbardziej Cię denerwują?',
  'Gdzie pieniądze są za las?',
  'Jaką muzykę grałby twój zespół?',
  'Jaką chciałbyś mieć supermoc?',
  'Jaki film obejrzałeś najwięcej razy?',
  'O spełnienie jakiego marzenia poprosiłbyś złotą rybkę?',
  'Jaka jest pierwsza rzecz, którą robisz rano?',
  'Jedzenie, które wszyscy lubią, a ty nie?',
  'Co przedstawiał twój ostatni rysunek?',
  'Ile lat chciałbyś żyć?',
  'Na jaką stronę internetową najczęściej wchodzisz?',
  'Twój największy celebrity crush?',
  'Co przedstawia osatnie zdjęcie w Twojej galerii?',
  'Gdybyś mógł nauczyć się jednego języka w jeden dzień, jaki by to był?',
  'Gdybyś mógł zakazać jednej rzeczy w Polsce - co by to było?',
  'Ulubiony fanpage na FB?',
  'Na co masz teraz ochotę?',
  'Co kupisz, jeśli byłoby cię stać na wszystko?',
  'Wymyśl sobie jakąś ksywkę - jaka byłaby?',
  'Kto z was jest najbardziej agresywny?',
  'Twój sekretny ulubiony wykonawca?',
  'Twoje ulubione określenie na zioło?',
  'Jak nazwałbyś swojego psa?',
  'Oprócz loda, środa to dzień...?',
  'Najbardziej egzotyczny narkotyk jakiego próbowałeś?',
  'Możesz zrobić coś całkowicie nielegalnego - co robisz?',
  'Co staje się lepsze z wiekiem?',
  'Są wyniki! Nową maskotką twojej uczelni zostaje...',
  'Nie ma takiej rzeczy jak...',
  'Co ukrywasz przed swoimi rodzicami?',
  'Co jest moją supermocą?',
  'Co jest najgorszą rzeczą która może się zdarzyć?',
  'Gdy jestem pijany, to uważam się za eksperta w ...?',
  'Dlaczego jesteś taki, jaki jesteś?',
  'Mam dużo problemów, ale jednym z nich nie jest...?',
  'Co nigdy nie zawodzi jeśli trzeba rozkręcić imprezę?',
  'Tylko dwie rzeczy są pewne w życiu: śmierć i ...?',
  'Nauka nigdy nie wyjaśni...?',
  'Co jest najlepszym przyjacielem kobiety?',
  'Co zamiast rózgi Święty Mikołaj zaczął rozdawać niegrzecznym dzieciom?',
  'Białasy lubią...',
  'Co naprawdę ssie?',
  'Hej mała, chodźmy do mnie to pokażę ci ___',
  'Twoja stara jest taka gruba że ___!',
  'Każdy problem można rozwiązać przy pomocy wystarczającej ilości ___',
  'Pierwsza randka, kawa. Druga randka, całus. Trzecia randka, ___',
  'Czym rekompensuję sobie mojego małego penisa?',
  'Uuu, tatuś lubi ___',
  'Cóż, jeśli ___ jest przestępstwem, to mnie zamknijcie!',
  'Co sprawia najwięcej problemów?',
  'Co sprawia, że jestem mokra?',
  'Jak ksywkę dałem swoim genitaliom?',
];

export const getRandomQueue = (queueLength = 8) => {
  const q = lodash.shuffle(questions);
  return q.slice(0, queueLength);
};

export const getShuffledQuestions = () => lodash.shuffle(questions);
